name: Spawn a shell

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-latest
          - macos-13
          - macos-12
          - macos-11
          - windows-latest
          - windows-2022
          - windows-2019
      authenticate:
        type: boolean
        description: 'Authenticated Access'
        required: false
        default: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          limit-access-to-actor: ${{ inputs.authenticate }}
      - name: Set up MSVC
        if: ${{ inputs.options == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1
